name: kv-cache-store CI 

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3

    - name: Installing Testing Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libffi-dev libgit2-dev -y 
        sudo apt-get install pkg-config meson ninja-build -y

    - name: Installing Testing Framework
      run: |
        sudo apt-get install libcriterion-dev
    - name: Installing libevent 
      run: |
        sudo wget https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz
        sudo tar -xzvf libevent-2.1.12-stable.tar.gz
    - name: Build libevent
      working-directory: libevent-2.1.12-stable.tar.gz
      run: |
        sudo mkdir build && cd build
        cmake ..
        make
        make install
    - name: Configure and Build CMake 
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Compile binaries
      working-directory: ${{github.workspace}}/build
      run: make clean all

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ./bin/kv-cache-store_tests --verbose
      
